FROM bitnami/spark:3.5

WORKDIR /app

USER root

RUN apt-get update && \
    apt-get install -y python3-pip gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY ../../requirements.txt .

RUN pip install --no-cache-dir --retries 10 --timeout 100 -r requirements.txt

COPY consumer.py .

USER 1001

CMD ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0", "consumer.py"]