
version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://flask-api:5000/api
    depends_on:
      - flask-api
    networks:
      - sentiment-network

  flask-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=sentiment_analysis
      - COLLECTION_NAME=predictions
    depends_on:
      - mongodb
    networks:
      - sentiment-network
      - bigdata-net

networks:
  sentiment-network:
    driver: bridge
  bigdata-net:
    external: true  # Utilise le réseau existant de votre docker-compose.yml backend
