FROM python:3.10-slim

# Configuration Java pour PySpark
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget gnupg2 && \
    wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor > /usr/share/keyrings/adoptium.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list && \
    apt-get update && \
    apt-get install -y temurin-8-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
WORKDIR /app
#ajoute recemment
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements.txt .
# Ajoute tout le contenu du backend dans /app
#COPY . /app

#COPY scripts/ scripts/
#COPY models/ models/ 
RUN pip install --no-cache-dir -r requirements.txt

# Copie de toute l'arborescence Backend
COPY . .

# Configuration Python
ENV PYTHONPATH=/app
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV PYSPARK_PYTHON=python3

EXPOSE 5000

# Exécution du point d'entrée unique
CMD ["python", "scripts/app.py"]