version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network

  flask-api:
    build:
      context: ..
      dockerfile: Backend/dockerfile
    container_name: flask-api
    depends_on:
      - mongodb
      - kafka
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - PORT=5000
      - SECRET_KEY=your_secret_key_here
      - ADMIN_KEY=your_admin_key_here
      - MODEL_PATH=/app/models/sentiment_model.pkl
      - VECTORIZER_PATH=/app/models/tfidf_vectorizer.pkl
    volumes:
      - ../Backend/models:/app/models
      - ../Backend/scripts:/app/scripts
      - ../Backend/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
